/**
 * Rate card — the first of the three vendor documents.
 *
 * The client's page 3: after the rate contract is filled and submitted, a
 * downloadable PDF carrying those same figures, ending in the From/To block
 * with the logged-in employee's name filled in for Sarva Express. The employee
 * sends it to the vendor and re-uploads it once it comes back signed.
 *
 * The figures are their "Img 1.1" table, in that order. A row the vendor's
 * contract doesn't use is left blank rather than shown as ₹0 — a zero on a rate
 * card reads as "free", which is not the same as "not applicable".
 */
import { BRAND } from './brand.js';

export interface RateCardParty {
  name: string;
  contact?: string | undefined;
  place?: string | undefined;
  phone?: string | undefined;
  email?: string | undefined;
  gstin?: string | undefined;
}

export interface RateCardFigures {
  avgMonthlyKm?: number | undefined;
  /** Free text — their own card reads "24 hrs /day", "Monthly Calendar Days
   *  (28-31 days)" and "At Actuals". None of those are numbers. */
  workingHrs?: string | undefined;
  workingDaysPerMonth?: string | undefined;
  vehicleType?: string | undefined;
  monthlyCostPaise?: number | undefined;
  extraKmPaise?: number | undefined;
  tollParking?: string | undefined;
}

const CSS = `
  * { box-sizing:border-box; }
  body { font-family:"Times New Roman", Georgia, serif; color:#111; margin:0; padding:48px 56px; font-size:13px; line-height:1.55; }
  h1 { text-align:center; font-size:16px; margin:0 0 4px; }
  .date { color:#555; font-size:12px; margin-bottom:16px; }
  .to p { margin:2px 0; }
  h2 { font-size:13px; margin:18px 0 6px; }
  table { width:100%; border-collapse:collapse; margin-top:6px; }
  td { border:1px solid #000; padding:7px 9px; font-size:12px; }
  td.k { width:55%; }
  td.v { font-weight:bold; }
  .sign { display:flex; justify-content:space-between; gap:40px; margin-top:48px; }
  .sign div { flex:1; font-size:12px; }
  .line { border-top:1px solid #000; margin-top:30px; padding-top:4px; }
  .foot { margin-top:26px; font-size:10px; color:#888; text-align:center; }
  @media print { body { padding:26px 30px; } }
`;

const fmtDate = (d: Date) => d.toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
/** Rupees from paise, grouped Indian-style. Blank when the row isn't used. */
const money = (paise?: number) => (paise ? `₹${(paise / 100).toLocaleString('en-IN')}` : '—');
const num = (n?: number) => (n ? String(n) : '—');
const text = (s?: string) => (s && s.trim() ? s.trim() : '—');

export function printRateCard(v: RateCardParty, r: RateCardFigures, employeeName?: string): void {
  // Row order is the client's Img 1.1, which is their own S L V rate card.
  const rows: [string, string][] = [
    ['Average Monthly KM', num(r.avgMonthlyKm)],
    ['Working hrs', text(r.workingHrs)],
    ['Working Days/Month', text(r.workingDaysPerMonth)],
    ['Vehicle Types', r.vehicleType ? r.vehicleType.replaceAll('_', ' ') : '—'],
    ['Monthly cost per Vehicle', money(r.monthlyCostPaise)],
    ['Extra KM Charge per Vehicle', money(r.extraKmPaise)],
    ['Toll / Parking', text(r.tollParking)],
  ];

  const inner = `
    <h1>Rate Card</h1>
    <div class="date">Date: ${fmtDate(new Date())}</div>
    <div class="to">
      <p><b>To,</b></p>
      <p>Vendor Company Name: ${v.name}</p>
      <p>Vendor Contact Name: ${v.contact || '____________________'}</p>
      <p>Vendor Address: ${v.place || '____________________'}</p>
      <p>Vendor Phone Number: ${v.phone || '____________________'}</p>
      ${v.gstin ? `<p>GSTIN: ${v.gstin}</p>` : ''}
    </div>

    <h2>Agreed rates</h2>
    <table>
      ${rows.map(([k, val]) => `<tr><td class="k">${k}</td><td class="v">${val}</td></tr>`).join('')}
    </table>

    <p>The rates above are the agreed transportation service cost and form Annexure B of the Service Agreement between ${BRAND.company} and ${v.name}. Any cost not listed here must be agreed in writing in advance.</p>

    <div class="sign">
      <div>From: <b>${BRAND.company}</b><div class="line">Name: ${employeeName || '____________________'}</div></div>
      <div>To: <b>${v.name}</b><div class="line">Name: ${v.contact || '____________________'}<br>Authorized signature</div></div>
    </div>
    <div class="foot">Generated by ${BRAND.company} · rate card. Sign and return a copy.</div>`;

  const bar = `<div class="__bar" style="position:sticky;top:0;z-index:9;display:flex;gap:10px;justify-content:center;align-items:center;background:#0F3D72;color:#fff;padding:9px;font-family:system-ui,sans-serif;font-size:13px;font-weight:600">Preview<button onclick="window.print()" style="padding:6px 16px;border:0;border-radius:6px;background:#fff;color:#0F3D72;font-weight:700;cursor:pointer">Print / Save as PDF</button></div>`;
  const w = window.open('', '_blank', 'width=860,height=1000');
  if (!w) { alert('Please allow pop-ups to preview the rate card.'); return; }
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Rate Card — ${v.name}</title><style>${CSS}@media print{.__bar{display:none!important}}</style></head><body>${bar}${inner}</body></html>`);
  w.document.close();
}
